docker: true
docker_image: "davidxd/yoko"
minimum_reviewers: 2
build_steps:
 - make clean deps compile
 - make test
 - make xref
 - make dialyzer
env:
 DIALYZER_PLT: .dialyzer_plt_a
merge: true
org_mode: true
timeout: 1790
