minimum_reviewers: 2
build_steps:
 - make clean deps compile
 - make test
 - make xref
 - DIALYZER_PLT=.dialyzer_plt_b make dialyzer
env:
 DIALYZER_PLT: .dialyzer_plt_a
merge: true
org_mode: true
timeout: 1790
